export type PaletteMode =
  | "free"
  | "pc98"
  | "pc98_tile"
  | "pc98_512"
  | "pc98_512_sat"
  | "pc98_4096"
  | "color32"
  | "color64"
  | "mono"
  | "neon"
  | "anime";
export type MonoTintMode = "gray" | "green" | "amber" | "ice";
export type PhosphorDotShape = "circle" | "heart";

export const MONO_TINTS: Record<
  MonoTintMode,
  { label: string; rgb: [number, number, number] }
> = {
  gray: { label: "Gray", rgb: [1, 1, 1] },
  green: { label: "Green", rgb: [0.72, 1, 0.58] },
  amber: { label: "Amber", rgb: [1, 0.82, 0.45] },
  ice: { label: "Ice", rgb: [0.7, 0.9, 1] },
};

export type RetroPresetDefinition = {
  label: string;
  width: number;
  height: number;
  colors: number;
  dither: number;
  palette: PaletteMode;
  curvature: number;
  scanline: number;
  scanline2: number;
  vignette: number;
  glow: number;
  smoothStrength?: number;
  toonSteps?: number;
  edgeBoost?: number;
  animeEdgeLow?: number;
  animeEdgeHigh?: number;
  phosphor: number;
  spotMask: number;
  bulbRadius: number;
  blackFloor: number;
  lumaAmount?: number;
  lumaLow?: number;
  lumaHigh?: number;
  lumaKnee?: number;
  saturationAmount?: number;
  saturationLow?: number;
  saturationHigh?: number;
  saturationKnee?: number;
  outputBrightness?: number;
  phosphorDotLightBalance?: number;
  phosphorDotShape?: PhosphorDotShape;
  phosphorDotInternalScale?: boolean;
  phosphorDotBrightCore?: boolean;
  phosphorDotCellFill?: number;
  phosphorDotFlatDisc?: boolean;
  phosphorDotNeighborBlend?: boolean;
  closeUpNoiseStrength?: number;
  scanlineBrightnessFade?: number;
  monoTint: MonoTintMode;
  neonBoost: number;
  neonSaturation: number;
  neonDetail: number;
  focusStrength?: number;
  focusWidth?: number;
  focusHeight?: number;
  featured?: boolean;
};

export const RETRO_PRESETS = {
  none: {
    label: "None",
    width: 1920,
    height: 1080,
    colors: 256,
    dither: 0,
    palette: "free" as const,
    curvature: 0,
    scanline: 0,
    scanline2: 0,
    vignette: 0,
    glow: 0,
    phosphor: 0,
    spotMask: 0,
    bulbRadius: 0,
    blackFloor: 0,
    monoTint: "gray" as const,
    neonBoost: 1,
    neonSaturation: 1,
    neonDetail: 1,
  },
  chunky: {
    label: "Chunky",
    featured: true,
    width: 256,
    height: 192,
    colors: 8,
    dither: 0.2,
    palette: "free",
    curvature: 0.0,
    scanline: 0.0,
    scanline2: 0.015,
    vignette: 0.04,
    glow: 0.03,
    phosphor: 0.03,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 0.8,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  arcade: {
    label: "Arcade",
    featured: true,
    width: 320,
    height: 224,
    colors: 12,
    dither: 0.28,
    palette: "free",
    curvature: 0.04,
    scanline: 0.08,
    scanline2: 0.0,
    vignette: 0.08,
    glow: 0.06,
    phosphor: 0.05,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 0.9,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  gb: {
    label: "GB",
    featured: true,
    width: 200, //GB is 160, // 160 or 144
    height: 180,// GB is 144,
    colors: 4,
    dither: 0.08,
    palette: "mono",
    curvature: 0.0,
    scanline: 0.0,
    scanline2: 0.0,
    vignette: 0.015,
    glow: 0.0,
    phosphor: 0.0,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "green",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  gba: {
    label: "GBA",
    featured: true,
    width: 320, // GBA is 240,GBA's internal resolution is 240x160, but we scale it to 320x200 for better visibility
    height: 200,// GBA is 160,
    colors: 48,
    dither: 0.06,
    palette: "free",
    curvature: 0.0,
    scanline: 0.0,
    scanline2: 0.0,
    vignette: 0.02,
    glow: 0.0,
    phosphor: 0.0,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  pc98_512: {
    label: "PC-98 512-color",
    width: 640,
    height: 400,
    colors: 8,
    dither: 0.12,
    palette: "pc98_512",
    curvature: 0.03,
    scanline: 0.00,
    scanline2: 0.02,
    vignette: 0.05,
    glow: 0.06,
    phosphor: 0.03,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  pc98_4096: {
    label: "PC-98 4096-color",
    width: 640,
    height: 400,
    colors: 16,
    dither: 0.08,
    palette: "pc98_4096",
    curvature: 0.03,
    scanline: 0.0,
    scanline2: 0.02,
    vignette: 0.05,
    glow: 0.05,
    phosphor: 0.03,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  pc98: {
    label: "Color 16",
    width: 640,
    height: 400,
    colors: 16,
    dither: 0.35,
    palette: "pc98",
    curvature: 0.02,
    scanline: 0.05,
    scanline2: 0.0,
    vignette: 0.06,
    glow: 0.05,
    phosphor: 0.04,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  pc98_tile: {
    label: "PC-98 Tile",
    width: 1280,
    height: 800,
    colors: 32,
    dither: 0.0,
    palette: "pc98_tile",
    curvature: 0.05,
    scanline: 0.0,
    scanline2: 0.01,
    vignette: 0.02,
    glow: 0.0,
    phosphor: 0.0,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  color32: {
    label: "Color 32",
    width: 320,
    height: 200,
    colors: 32,
    dither: 0.24,
    palette: "color32",
    curvature: 0.03,
    scanline: 0.06,
    scanline2: 0.0,
    vignette: 0.05,
    glow: 0,
    phosphor: 0.03,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  color64: {
    label: "Color 64",
    width: 320,
    height: 200,
    colors: 64,
    dither: 0.2,
    palette: "color64",
    curvature: 0.03,
    scanline: 0.04,
    scanline2: 0.0,
    vignette: 0.04,
    glow: 0,
    phosphor: 0.03,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  monochrome: {
    label: "Mono",
    width: 640,
    height: 400,
    colors: 16,
    dither: 0.18,
    palette: "mono",
    curvature: 0.0,
    scanline: 0.0,
    scanline2: 0.0,
    vignette: 0.015,
    glow: 0.0,
    phosphor: 0.0,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  greenTerminal: {
    label: "Green Terminal",
    width: 640,
    height: 400,
    colors: 16,
    dither: 0.14,
    palette: "mono",
    curvature: 0.07,
    scanline: 0.16,
    scanline2: 0.0,
    vignette: 0.1,
    glow: 0.09,
    phosphor: 0.06,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "green",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  amberCrt: {
    label: "Amber CRT",
    featured: true,
    width: 960,
    height: 600,
    colors: 32,
    dither: 0.16,
    palette: "mono",
    curvature: 0.06,
    scanline: 0.0,
    scanline2: 0.02,
    vignette: 0.11,
    glow: 0.10,
    phosphor: 0.05,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "amber",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  neonLine: {
    label: "Neon Line",
    width: 960,
    height: 540,
    colors: 24,
    dither: 0.0,
    palette: "neon",
    curvature: 0.0,
    scanline: 0.0,
    scanline2: 0.0,
    vignette: 0.04,
    glow: 0.18,
    phosphor: 0.0,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "ice",
    neonBoost: 1.15,
    neonSaturation: 1.2,
    neonDetail: 1.05,
  },
  lcdIce: {
    label: "LCD Ice",
    featured: true,
    width: 480,
    height: 300,
    colors: 16,
    dither: 0.06,
    palette: "mono",
    curvature: 0.0,
    scanline: 0.00,
    scanline2: 0.00,
    vignette: 0.015,
    glow: 0.00,
    phosphor: 0.00,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "ice",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  phosphorDotLite: {
    label: "Phosphor Dot Lite",
    featured: true,
    width: 320,
    height: 180,
    colors: 32,
    dither: 0.0,
    palette: "free",
    curvature: 0.02,
    scanline: 0.0,
    scanline2: 0.00,
    vignette: 0.00,
    glow: 0.28,
    phosphor: 0.0,
    spotMask: 0.22,
    bulbRadius: 0.38,
    blackFloor: 0.002,
    phosphorDotShape: "heart",  
    phosphorDotLightBalance: 0.16,
    phosphorDotInternalScale: true,
    phosphorDotBrightCore: true,
    phosphorDotCellFill: 0.28,
    phosphorDotFlatDisc: false,
    phosphorDotNeighborBlend: true,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
    outputBrightness: 1.0,
  },
  phosphorDot: {
    label: "Phosphor Dot",
    featured: true,
    width: 320,
    height: 180,
    colors: 32,
    dither: 0.0,
    palette: "free",
    curvature: 0.065,
    scanline: 0.0,
    scanline2: 0.02,
    vignette: 0.3,
    glow: 0.08,
    phosphor: 0.0,
    spotMask: 0.3,
    bulbRadius: 0.5,
    blackFloor: 0.001,
    phosphorDotLightBalance: 0.22,
    phosphorDotInternalScale: true,
    phosphorDotBrightCore: false,
    phosphorDotCellFill: 0.12,
    phosphorDotFlatDisc: true,
    phosphorDotNeighborBlend: true,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
    outputBrightness: 1.8,
  },
  crtOnly: {
    label: "CRT Only",
    width: 1280,
    height: 800,
    colors: 256,
    dither: 0.12,
    palette: "free",
    curvature: 0.03,
    scanline: 0.00,
    scanline2: 0.02,
    vignette: 0.05,
    glow: 0.06,
    phosphor: 0.03,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  crtEdge: {
    label: "CRT Edge",
    featured: true,
    width: 1280,
    height: 800,
    colors: 256,
    dither: 0.12,
    palette: "free",
    curvature: 0.03,
    scanline: 0.00,
    scanline2: 0.06,
    vignette: 0.48,
    glow: 0.28,
    edgeBoost: 0.68,
    phosphor: 0.48,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
    closeUpNoiseStrength: 1.2,
    scanlineBrightnessFade: 0.98
  },
  animeCel: {
    label: "Anime Cel",
    width: 640,
    height: 360,
    colors: 16,
    dither: 0.0,
    palette: "anime",
    curvature: 0.0,
    scanline: 0.0,
    scanline2: 0.0,
    vignette: 0.0,
    glow: 0.0,
    smoothStrength: 0.15,
    toonSteps: 1,
    edgeBoost: 0.3,
    animeEdgeLow: 0.22,
    animeEdgeHigh: 0.66,
    phosphor: 0.0,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.0,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  tetorica: {
    label: "Tetorica",
    featured: true,
    width: 1280,
    height: 800,
    colors: 256,
    dither: 0.12,
    palette: "free",
    curvature: 0.03,
    scanline: 0.00,
    scanline2: 0.12,
    vignette: 0.48,
    glow: 0.28,
    toonSteps: 3,
    edgeBoost: 1.5,
    animeEdgeLow: 0.08,
    animeEdgeHigh: 0.55,
    phosphor: 0.48,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
    closeUpNoiseStrength: 1.8,
    scanlineBrightnessFade: 0.92,
  },
  animeToon: {
    label: "Anime Toon",
    width: 640,
    height: 360,
    colors: 8,
    dither: 0.0,
    palette: "free",
    curvature: 0.0,
    scanline: 0.0,
    scanline2: 0.0,
    vignette: 0.0,
    glow: 0.0,
    smoothStrength: 0.35,
    toonSteps: 8,
    edgeBoost: 0.22,
    animeEdgeLow: 0.08,
    animeEdgeHigh: 0.55,
    phosphor: 0.0,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.008,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
  },
  warmBokeh: {
    label: "Warm Bokeh",
    width: 960,
    height: 540,
    colors: 64,
    dither: 0.06,
    palette: "free",
    curvature: 0.05,
    scanline: 0.02,
    scanline2: 0.01,
    vignette: 0.28,
    glow: 0.14,
    phosphor: 0.04,
    spotMask: 0.0,
    bulbRadius: 0.3,
    blackFloor: 0.005,
    monoTint: "gray",
    neonBoost: 1.0,
    neonSaturation: 1.0,
    neonDetail: 1.0,
    focusStrength: 0.28,
    focusWidth: 0.24,
    focusHeight: 0.16,
    saturationAmount: 0.35,
    saturationLow: 0.0,
    saturationHigh: 0.35,
    saturationKnee: 0.5,
  },
} as const satisfies Record<
  string,
  RetroPresetDefinition
>;

export type RetroPresetKey = keyof typeof RETRO_PRESETS;

// Single source of truth for "which preset is the app's default".
// Change this one line to try a different default; every consumer (initial
// filter state, saved-settings fallback, etc.) resolves through this key.
export const defaultPresetId: RetroPresetKey = "phosphorDot";
// デフォルト候補: "phosphorDot";//"tetorica";

// Grouping used by the preset picker UI. "none" is intentionally excluded —
// it's rendered outside the category boxes as a plain "no filter" option.
export type RetroPresetCategory = "classic" | "lcd" | "crt" | "other";

export const RETRO_PRESET_CATEGORY_LABELS: Record<RetroPresetCategory, string> = {
  classic: "Game / Classic",
  lcd: "LCD",
  crt: "CRT",
  other: "Other",
};

export const RETRO_PRESET_CATEGORY_ORDER: RetroPresetCategory[] = [
  "classic",
  "lcd",
  "crt",
  "other",
];

export const RETRO_PRESET_CATEGORIES = {
  chunky: "classic",
  arcade: "classic",
  gb: "classic",
  gba: "classic",
  pc98_512: "classic",
  pc98_4096: "classic",
  pc98: "classic",
  pc98_tile: "classic",
  color32: "classic",
  color64: "classic",
  monochrome: "lcd",
  lcdIce: "lcd",
  greenTerminal: "crt",
  amberCrt: "crt",
  phosphorDotLite: "crt",
  phosphorDot: "crt",
  crtOnly: "crt",
  crtEdge: "crt",
  warmBokeh: "crt",
  neonLine: "other",
  animeCel: "other",
  animeToon: "other",
  tetorica: "other",
} as const satisfies Record<Exclude<RetroPresetKey, "none">, RetroPresetCategory>;

export const paletteModeToUniform = (mode: PaletteMode) => {
  if (mode === "pc98") return 1;
  if (mode === "pc98_tile") return 2;
  if (mode === "pc98_512") return 3;
  if (mode === "pc98_512_sat") return 4;
  if (mode === "pc98_4096") return 5;
  if (mode === "color32") return 6;
  if (mode === "color64") return 7;
  if (mode === "mono") return 8;
  if (mode === "neon") return 9;
  if (mode === "anime") return 10;

  return 0;
};
