// Generated by scripts/sync-extension-shader.mjs from src/retro-player/retro/filterPass1LiteShader.ts
export const FILTER_FRAGMENT_PASS1_LITE = `#version 300 es
precision mediump float;

in vec2 vTextureCoord;
out vec4 finalColor;

uniform sampler2D uTexture;
uniform vec2 uTargetSize;
uniform float uColorLevels;
uniform float uDitherStrength;
uniform float uSamplingMode;
uniform float uPaletteMode;
uniform float uHorizontalSharpness;
uniform float uRgbConvergenceOffset;
uniform float uSmoothStrength;
uniform float uToonSteps;
uniform float uEdgeBoost;
uniform float uAnimeEdgeLow;
uniform float uAnimeEdgeHigh;
uniform vec3 uMonoTint;
uniform float uNeonBoost;
uniform float uNeonSaturation;
uniform float uNeonDetail;
uniform float uGlowStrength;
uniform float uColoredGlowEnabled;
uniform float uCompositeEnabled;
uniform float uCompositeAmount;
uniform float uCompositeChromaBlur;
uniform float uCompositeChromaDelay;
uniform float uCompositeNoise;
uniform float uTime;

float bayer4x4(vec2 pos)
{
  int x = int(mod(pos.x, 4.0));
  int y = int(mod(pos.y, 4.0));
  int index = y * 4 + x;
  float matrix[16];
  matrix[0] = 0.0 / 16.0;
  matrix[1] = 8.0 / 16.0;
  matrix[2] = 2.0 / 16.0;
  matrix[3] = 10.0 / 16.0;
  matrix[4] = 12.0 / 16.0;
  matrix[5] = 4.0 / 16.0;
  matrix[6] = 14.0 / 16.0;
  matrix[7] = 6.0 / 16.0;
  matrix[8] = 3.0 / 16.0;
  matrix[9] = 11.0 / 16.0;
  matrix[10] = 1.0 / 16.0;
  matrix[11] = 9.0 / 16.0;
  matrix[12] = 15.0 / 16.0;
  matrix[13] = 7.0 / 16.0;
  matrix[14] = 13.0 / 16.0;
  matrix[15] = 5.0 / 16.0;
  return matrix[index];
}

vec2 targetCellUv(vec2 cell)
{
  return clamp((cell + 0.5) / max(uTargetSize, vec2(1.0)), vec2(0.0), vec2(1.0));
}

vec3 sampleCellAverage4(vec2 cellMin, vec2 cellSize)
{
  vec2 quarter = cellSize * 0.25;
  vec3 sum = vec3(0.0);
  sum += texture(uTexture, clamp(cellMin + vec2(quarter.x, quarter.y), vec2(0.0), vec2(1.0))).rgb;
  sum += texture(uTexture, clamp(cellMin + vec2(cellSize.x - quarter.x, quarter.y), vec2(0.0), vec2(1.0))).rgb;
  sum += texture(uTexture, clamp(cellMin + vec2(quarter.x, cellSize.y - quarter.y), vec2(0.0), vec2(1.0))).rgb;
  sum += texture(uTexture, clamp(cellMin + vec2(cellSize.x - quarter.x, cellSize.y - quarter.y), vec2(0.0), vec2(1.0))).rgb;
  return sum * 0.25;
}

vec3 sampleCellAverage8(vec2 cellMin, vec2 cellSize)
{
  vec3 sum = vec3(0.0);
  sum += texture(uTexture, clamp(cellMin + cellSize * vec2(0.25, 0.25), vec2(0.0), vec2(1.0))).rgb;
  sum += texture(uTexture, clamp(cellMin + cellSize * vec2(0.75, 0.25), vec2(0.0), vec2(1.0))).rgb;
  sum += texture(uTexture, clamp(cellMin + cellSize * vec2(0.25, 0.75), vec2(0.0), vec2(1.0))).rgb;
  sum += texture(uTexture, clamp(cellMin + cellSize * vec2(0.75, 0.75), vec2(0.0), vec2(1.0))).rgb;
  sum += texture(uTexture, clamp(cellMin + cellSize * vec2(0.50, 0.20), vec2(0.0), vec2(1.0))).rgb;
  sum += texture(uTexture, clamp(cellMin + cellSize * vec2(0.50, 0.80), vec2(0.0), vec2(1.0))).rgb;
  sum += texture(uTexture, clamp(cellMin + cellSize * vec2(0.20, 0.50), vec2(0.0), vec2(1.0))).rgb;
  sum += texture(uTexture, clamp(cellMin + cellSize * vec2(0.80, 0.50), vec2(0.0), vec2(1.0))).rgb;
  return sum * 0.125;
}

vec3 sampleCellAverage16(vec2 cellMin, vec2 cellSize)
{
  vec3 sum = vec3(0.0);
  for (int y = 0; y < 4; y++) {
    for (int x = 0; x < 4; x++) {
      vec2 offset = (vec2(float(x), float(y)) + 0.5) / 4.0;
      sum += texture(uTexture, clamp(cellMin + cellSize * offset, vec2(0.0), vec2(1.0))).rgb;
    }
  }
  return sum * (1.0 / 16.0);
}

vec3 sampleBaseSourceColorAtCell(vec2 cell)
{
  vec2 safeTargetSize = max(uTargetSize, vec2(1.0));
  vec2 uv = targetCellUv(cell);
  if (uSamplingMode < 0.5) {
    return texture(uTexture, uv).rgb;
  }

  vec2 clampedCell = clamp(cell, vec2(0.0), safeTargetSize - vec2(1.0));
  vec2 cellMin = clampedCell / safeTargetSize;
  vec2 cellSize = 1.0 / safeTargetSize;
  if (uSamplingMode < 1.5) {
    return sampleCellAverage4(cellMin, cellSize);
  }
  if (uSamplingMode < 2.5) {
    return sampleCellAverage8(cellMin, cellSize);
  }
  return sampleCellAverage8(cellMin, cellSize);
}

vec3 sampleSourceColorAtCell(vec2 cell)
{
  vec3 center = sampleBaseSourceColorAtCell(cell);
  if (uSmoothStrength <= 0.001) {
    return center;
  }

  vec3 left = sampleBaseSourceColorAtCell(cell + vec2(-1.0, 0.0));
  vec3 right = sampleBaseSourceColorAtCell(cell + vec2(1.0, 0.0));
  vec3 up = sampleBaseSourceColorAtCell(cell + vec2(0.0, -1.0));
  vec3 down = sampleBaseSourceColorAtCell(cell + vec2(0.0, 1.0));
  vec3 blurred = center * 0.4 + (left + right + up + down) * 0.15;
  return mix(center, blurred, clamp(uSmoothStrength, 0.0, 1.0));
}

vec3 sampleConvergedColor(vec2 uv, vec2 texel)
{
  if (uRgbConvergenceOffset <= 0.0001) {
    return texture(uTexture, uv).rgb;
  }

  vec2 offset = vec2(texel.x * uRgbConvergenceOffset, 0.0);
  float r = texture(uTexture, clamp(uv + offset, vec2(0.0), vec2(1.0))).r;
  float g = texture(uTexture, uv).g;
  float b = texture(uTexture, clamp(uv - offset, vec2(0.0), vec2(1.0))).b;
  return vec3(r, g, b);
}

vec3 applyHorizontalSharpness(vec3 center, vec3 left, vec3 right)
{
  float amount = clamp(uHorizontalSharpness - 1.0, -1.0, 1.0);
  if (abs(amount) <= 0.0001) {
    return center;
  }

  vec3 horizontalBlur = (left + center * 2.0 + right) * 0.25;
  if (amount < 0.0) {
    return mix(center, horizontalBlur, -amount);
  }

  vec3 sharpened = center + (center - 0.5 * (left + right)) * amount;
  return clamp(sharpened, 0.0, 1.0);
}

vec3 applyToonShading(vec3 color, float steps)
{
  if (steps < 2.0) {
    return color;
  }

  float luminance = dot(color, vec3(0.299, 0.587, 0.114));
  float stepped = floor(luminance * (steps - 1.0) + 0.5) / max(steps - 1.0, 1.0);
  float scale = stepped / max(luminance, 0.001);
  return clamp(mix(color, color * scale, 0.88), 0.0, 1.0);
}

vec3 monochromePalette(vec3 color, float levels, vec3 tint)
{
  float luminance = dot(color, vec3(0.299, 0.587, 0.114));
  float stepped = floor(luminance * (levels - 1.0) + 0.5) / max(levels - 1.0, 1.0);
  return clamp(tint * stepped, 0.0, 1.0);
}

vec3 quantizeColor(vec3 color, float levels)
{
  return floor(color * (levels - 1.0) + 0.5) / max(levels - 1.0, 1.0);
}

vec3 nearestColor32(vec3 color)
{
  return vec3(
    round(color.r * 3.0) / 3.0,
    round(color.g * 3.0) / 3.0,
    round(color.b)
  );
}

vec3 nearestColor64(vec3 color)
{
  return round(color * 3.0) / 3.0;
}

vec3 rgb2hsv(vec3 c)
{
  vec4 K = vec4(0.0, -1.0/3.0, 2.0/3.0, -1.0);
  vec4 p = mix(vec4(c.bg, K.wz), vec4(c.gb, K.xy), step(c.b, c.g));
  vec4 q = mix(vec4(p.xyw, c.r), vec4(c.r, p.yzx), step(p.x, c.r));
  float d = q.x - min(q.w, q.y);
  return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + 1.0e-10)), d / (q.x + 1.0e-10), q.x);
}

vec3 hsv2rgb(vec3 c)
{
  vec4 K = vec4(1.0, 2.0/3.0, 1.0/3.0, 3.0);
  vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
  return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
}

vec3 adjustSaturation(vec3 color, float saturation)
{
  float luminance = dot(color, vec3(0.299, 0.587, 0.114));
  return mix(vec3(luminance), color, saturation);
}

vec3 rgbToYiq(vec3 color)
{
  return vec3(
    dot(color, vec3(0.299, 0.587, 0.114)),
    dot(color, vec3(0.596, -0.275, -0.321)),
    dot(color, vec3(0.212, -0.523, 0.311))
  );
}

vec3 yiqToRgb(vec3 yiq)
{
  return vec3(
    yiq.x + 0.956 * yiq.y + 0.621 * yiq.z,
    yiq.x - 0.272 * yiq.y - 0.647 * yiq.z,
    yiq.x - 1.106 * yiq.y + 1.703 * yiq.z
  );
}

float hash12(vec2 p)
{
  vec3 p3 = fract(vec3(p.xyx) * 0.1031);
  p3 += dot(p3, p3.yzx + 33.33);
  return fract((p3.x + p3.y) * p3.z);
}

vec3 applyCompositeNtsc(vec2 cell, vec3 centerColor)
{
  if (uCompositeEnabled < 0.5 || uCompositeAmount <= 0.001) {
    return centerColor;
  }

  vec3 centerYiq = rgbToYiq(centerColor);
  vec3 left1Yiq = rgbToYiq(sampleSourceColorAtCell(cell + vec2(-1.0, 0.0)));
  vec3 right1Yiq = rgbToYiq(sampleSourceColorAtCell(cell + vec2(1.0, 0.0)));
  vec3 left2Yiq = rgbToYiq(sampleSourceColorAtCell(cell + vec2(-2.0, 0.0)));
  vec3 right2Yiq = rgbToYiq(sampleSourceColorAtCell(cell + vec2(2.0, 0.0)));
  vec3 left3Yiq = rgbToYiq(sampleSourceColorAtCell(cell + vec2(-3.0, 0.0)));
  vec3 right3Yiq = rgbToYiq(sampleSourceColorAtCell(cell + vec2(3.0, 0.0)));

  float blur = clamp(uCompositeChromaBlur, 0.0, 1.0);
  float delay = clamp(uCompositeChromaDelay, -1.0, 1.0);
  float amount = clamp(uCompositeAmount, 0.0, 1.0);
  float frame = floor(uTime * 60.0);
  float frameMed = floor(uTime * 19.0);
  float frameSlow = floor(uTime * 7.0);
  float linePhase = hash12(vec2(cell.y * 0.73 + 19.0, frame * 0.19 + frameSlow * 0.61)) - 0.5;
  float lineDrift = hash12(vec2(cell.y * 1.91 + 7.0, frameSlow + 41.0)) - 0.5;
  float lineBurst = hash12(vec2(cell.y * 3.17 + 3.0, frameMed + 113.0)) - 0.5;
  float chromaJitter = hash12(cell + vec2(frame * 0.618, frameMed * 1.731)) - 0.5;
  float jitterBurst = hash12(cell.yx + vec2(frameMed * 0.37, frameSlow * 2.13)) - 0.5;
  delay = clamp(delay + (chromaJitter * 0.1 + jitterBurst * 0.06) * amount, -1.0, 1.0);
  blur = clamp(blur + (linePhase * 0.032 + lineDrift * 0.022 + lineBurst * 0.018) * amount, 0.0, 1.0);

  vec2 preferredDir = delay >= 0.0 ? vec2(1.0, 0.0) : vec2(-1.0, 0.0);
  vec3 delayNearYiq = rgbToYiq(sampleSourceColorAtCell(cell + preferredDir));
  vec3 delayFarYiq = rgbToYiq(sampleSourceColorAtCell(cell + preferredDir * 2.0));
  vec3 delayFartherYiq = rgbToYiq(sampleSourceColorAtCell(cell + preferredDir * 3.0));
  vec3 ghostNearYiq = rgbToYiq(sampleSourceColorAtCell(cell + preferredDir * 4.0));
  vec3 ghostFarYiq = rgbToYiq(sampleSourceColorAtCell(cell + preferredDir * 6.0));
  vec2 chromaCenter = centerYiq.yz;
  vec2 chromaBlurred =
    chromaCenter * (1.0 - blur * 1.15) +
    (left1Yiq.yz + right1Yiq.yz) * (0.32 * blur) +
    (left2Yiq.yz + right2Yiq.yz) * (0.16 * blur) +
    (left3Yiq.yz + right3Yiq.yz) * (0.08 * blur);
  vec2 delayedChroma = mix(chromaBlurred, delayNearYiq.yz, abs(delay) * 0.95);
  delayedChroma = mix(delayedChroma, delayFarYiq.yz, abs(delay) * 0.55);
  delayedChroma = mix(delayedChroma, delayFartherYiq.yz, abs(delay) * 0.28);

  float chromaNoise = (hash12(
    cell + vec2(centerYiq.x, delayedChroma.x) * 97.0 + vec2(frame * 0.11, frame * 0.07)
  ) - 0.5)
    * 0.14 * clamp(uCompositeNoise, 0.0, 1.0);
  delayedChroma += vec2(chromaNoise, -chromaNoise * 0.85);

  float lumaEdge = abs(right1Yiq.x - left1Yiq.x) + abs(right2Yiq.x - left2Yiq.x) * 0.5;
  float chromaCross = smoothstep(0.04, 0.32, lumaEdge) * (0.04 + blur * 0.1) * amount;
  float subcarrierFlip = hash12(vec2(cell.y * 2.0 + mod(cell.x, 4.0), frameMed + 211.0)) > 0.5 ? 1.0 : -1.0;
  vec2 crawlTint = vec2(
    hash12(cell + vec2(frame * 0.23, 17.0)),
    hash12(cell.yx + vec2(frame * 0.17, 53.0))
  ) - 0.5;
  crawlTint *= chromaCross * vec2(1.0, 0.85) * subcarrierFlip;
  delayedChroma += crawlTint;

  float lumaLeak = 0.18 * amount;
  float compositeLuma =
    centerYiq.x * (1.0 - lumaLeak) +
    (left1Yiq.x + right1Yiq.x) * (0.36 * lumaLeak) +
    (left2Yiq.x + right2Yiq.x) * (0.14 * lumaLeak);
  float chromaMagnitude = length(delayedChroma);
  compositeLuma +=
    (hash12(cell + vec2(frame * 0.19, chromaMagnitude * 23.0)) - 0.5) *
    smoothstep(0.08, 0.45, chromaMagnitude) *
    0.035 *
    amount;

  vec3 compositeRgb = yiqToRgb(vec3(compositeLuma, delayedChroma));
  vec3 bleedRgb = yiqToRgb(vec3(centerYiq.x, delayedChroma));
  float ghostStrength = amount * (0.035 + clamp(uCompositeNoise, 0.0, 1.0) * 0.08 + abs(delay) * 0.03);
  vec3 ghostRgb =
    yiqToRgb(vec3(ghostNearYiq.x, ghostNearYiq.yz)) * 0.7 +
    yiqToRgb(vec3(ghostFarYiq.x, ghostFarYiq.yz)) * 0.3;
  vec3 pushedRgb = mix(compositeRgb, bleedRgb, 0.42 + blur * 0.2);
  pushedRgb += ghostRgb * ghostStrength;
  return clamp(mix(centerColor, pushedRgb, amount * 0.95), 0.0, 1.0);
}

vec3 nearestColorAnime(vec3 color)
{
  vec3 hsv = rgb2hsv(color);
  float h = hsv.x;
  float s = hsv.y;
  float v = hsv.z;

  float skinWeight = max(
    1.0 - smoothstep(0.05, 0.10, h),
    smoothstep(0.90, 0.95, h)
  ) * smoothstep(0.08, 0.20, s);

  float vQ = 0.22 + round(v * 2.0) / 2.0 * 0.72;

  float shadowDepth = max(0.0, v - vQ);
  float hQ = fract(h + skinWeight * shadowDepth * 0.12);

  float satScale = mix(1.35, 0.85, vQ);
  float sQ = clamp(s * satScale, 0.0, 1.0);

  return hsv2rgb(vec3(hQ, sQ, vQ));
}

// Palette quantization for all modes except neon (mode 9), which uses its own
// edge-based tint instead of quantizing a sampled color. Shared between the
// center pixel and the raw neighbor samples used by the glow pass below.
vec3 applyPaletteMode(vec3 color)
{
  if (uPaletteMode > 7.5 && uPaletteMode < 8.5) {
    return monochromePalette(color, max(uColorLevels, 2.0), uMonoTint);
  } else if (uPaletteMode > 9.5 && uPaletteMode < 10.5) {
    return nearestColorAnime(color);
  } else if (uPaletteMode > 10.5) {
    return quantizeColor(color, max(min(uColorLevels, 24.0), 6.0));
  } else if (uPaletteMode > 5.5 && uPaletteMode < 6.5) {
    return nearestColor32(color);
  } else if (uPaletteMode > 6.5 && uPaletteMode < 7.5) {
    return nearestColor64(color);
  }

  return quantizeColor(color, max(uColorLevels, 2.0));
}

float computeSourceEdge(vec2 uv, vec2 texel)
{
  float tl = dot(texture(uTexture, clamp(uv + vec2(-texel.x, -texel.y), vec2(0.0), vec2(1.0))).rgb, vec3(0.299, 0.587, 0.114));
  float tc = dot(texture(uTexture, clamp(uv + vec2( 0.0,     -texel.y), vec2(0.0), vec2(1.0))).rgb, vec3(0.299, 0.587, 0.114));
  float tr = dot(texture(uTexture, clamp(uv + vec2( texel.x, -texel.y), vec2(0.0), vec2(1.0))).rgb, vec3(0.299, 0.587, 0.114));
  float ml = dot(texture(uTexture, clamp(uv + vec2(-texel.x,  0.0    ), vec2(0.0), vec2(1.0))).rgb, vec3(0.299, 0.587, 0.114));
  float mr = dot(texture(uTexture, clamp(uv + vec2( texel.x,  0.0    ), vec2(0.0), vec2(1.0))).rgb, vec3(0.299, 0.587, 0.114));
  float bl = dot(texture(uTexture, clamp(uv + vec2(-texel.x,  texel.y), vec2(0.0), vec2(1.0))).rgb, vec3(0.299, 0.587, 0.114));
  float bc = dot(texture(uTexture, clamp(uv + vec2( 0.0,      texel.y), vec2(0.0), vec2(1.0))).rgb, vec3(0.299, 0.587, 0.114));
  float br = dot(texture(uTexture, clamp(uv + vec2( texel.x,  texel.y), vec2(0.0), vec2(1.0))).rgb, vec3(0.299, 0.587, 0.114));

  float gx = -tl + tr - 2.0 * ml + 2.0 * mr - bl + br;
  float gy = -tl - 2.0 * tc - tr + bl + 2.0 * bc + br;
  return clamp(length(vec2(gx, gy)), 0.0, 1.0);
}

vec3 applyNeonLinePalette(vec2 uv, vec2 texel, float levels, vec3 monoTint)
{
  vec3 center = texture(uTexture, uv).rgb;
  vec3 left = texture(uTexture, clamp(uv - vec2(texel.x, 0.0), vec2(0.0), vec2(1.0))).rgb;
  vec3 right = texture(uTexture, clamp(uv + vec2(texel.x, 0.0), vec2(0.0), vec2(1.0))).rgb;
  vec3 up = texture(uTexture, clamp(uv - vec2(0.0, texel.y), vec2(0.0), vec2(1.0))).rgb;
  vec3 down = texture(uTexture, clamp(uv + vec2(0.0, texel.y), vec2(0.0), vec2(1.0))).rgb;

  float centerLum = dot(center, vec3(0.299, 0.587, 0.114));
  float leftLum = dot(left, vec3(0.299, 0.587, 0.114));
  float rightLum = dot(right, vec3(0.299, 0.587, 0.114));
  float upLum = dot(up, vec3(0.299, 0.587, 0.114));
  float downLum = dot(down, vec3(0.299, 0.587, 0.114));

  float gradient = length(vec2(rightLum - leftLum, downLum - upLum));
  float detailScale = mix(2.0, 4.2, clamp(uNeonDetail - 0.5, 0.0, 1.5) / 1.5);
  float edge = pow(
    clamp(gradient * detailScale, 0.0, 1.0),
    mix(0.95, 0.58, clamp(uNeonDetail, 0.0, 2.0) * 0.5)
  );
  float silhouette = smoothstep(0.18, 0.8, centerLum);
  float line = clamp(edge + silhouette * 0.2, 0.0, 1.0);
  float stepped = floor(line * (levels - 1.0) + 0.5) / max(levels - 1.0, 1.0);

  vec3 tintCore = adjustSaturation(monoTint, 1.14);
  vec3 tintWarm = vec3(
    monoTint.r,
    max(monoTint.g * 0.62, 0.04),
    max(monoTint.b * 0.28, 0.02)
  );
  vec3 tintCool = vec3(
    max(monoTint.r * 0.34, 0.03),
    monoTint.g * 0.82,
    monoTint.b
  );
  float tintVariance = max(max(monoTint.r, monoTint.g), monoTint.b)
    - min(min(monoTint.r, monoTint.g), monoTint.b);
  vec3 tintAccent = adjustSaturation(
    mix(tintCool, tintWarm, smoothstep(0.52, 0.9, monoTint.r)),
    1.28
  );
  vec3 neonCore = vec3(0.08, 0.94, 1.0);
  vec3 neonAccent = vec3(1.0, 0.16, 0.82);
  vec3 primary = mix(neonCore, tintCore, 0.56);
  vec3 accent = mix(neonAccent, tintAccent, clamp(tintVariance * 1.85, 0.18, 0.82));
  vec3 backgroundTint = mix(vec3(0.01, 0.012, 0.03), tintCore * vec3(0.09, 0.07, 0.13), 0.38);
  vec3 background = mix(
    backgroundTint,
    backgroundTint + neonAccent * 0.06 + accent * 0.04,
    silhouette * 0.18
  );
  vec3 beamBase = mix(primary, accent, smoothstep(0.2, 1.0, centerLum + edge * 0.6));
  float saturation = clamp(uNeonSaturation, 0.0, 2.5);
  vec3 beam = adjustSaturation(beamBase, saturation);
  float boost = clamp(uNeonBoost, 0.0, 2.5);
  vec3 haloBase = mix(primary, accent, 0.72);
  vec3 halo = adjustSaturation(haloBase, 0.65 + saturation * 0.8)
    * pow(stepped, 1.8 + boost * 0.35)
    * (0.40 + boost * 0.23);

  vec3 neon = background + beam * stepped * (0.7 + boost * 0.45) + halo;
  return adjustSaturation(neon, 0.85 + saturation * 0.35);
}

void main(void)
{
  vec2 cell = floor(vTextureCoord * uTargetSize);
  vec2 pixelatedUv = targetCellUv(cell);
  vec2 texel = 1.0 / max(uTargetSize, vec2(1.0));

  vec3 sourceColor = sampleSourceColorAtCell(cell);
  if (uRgbConvergenceOffset > 0.0001) {
    vec3 center = sourceColor;
    float r = sampleSourceColorAtCell(cell + vec2(uRgbConvergenceOffset, 0.0)).r;
    float b = sampleSourceColorAtCell(cell + vec2(-uRgbConvergenceOffset, 0.0)).b;
    sourceColor = vec3(r, center.g, b);
  }
  sourceColor = applyCompositeNtsc(cell, sourceColor);
  vec3 leftSharp = sampleSourceColorAtCell(cell + vec2(-1.0, 0.0));
  vec3 rightSharp = sampleSourceColorAtCell(cell + vec2(1.0, 0.0));
  vec3 color = applyHorizontalSharpness(sourceColor, leftSharp, rightSharp);
  float dither = (bayer4x4(cell) - 0.5) * (uDitherStrength / max(uColorLevels, 1.0));
  color = clamp(color + dither, 0.0, 1.0);
  color = applyToonShading(color, uToonSteps);

  bool isNeon = uPaletteMode > 8.5 && uPaletteMode < 9.5;

  if (isNeon) {
    color = applyNeonLinePalette(pixelatedUv, texel, max(uColorLevels, 2.0), uMonoTint);
    if (uGlowStrength > 0.001) {
      vec3 halo = applyNeonLinePalette(
        clamp(pixelatedUv + vec2(texel.x * 0.5, texel.y * 0.5), vec2(0.0), vec2(1.0)),
        texel,
        max(uColorLevels, 2.0),
        uMonoTint
      );
      color = mix(
        color,
        color + halo * uGlowStrength * (0.35 + uNeonBoost * 0.22),
        0.45
      );
    }
  } else {
    color = applyPaletteMode(color);

    if (uGlowStrength > 0.001) {
      vec3 glow = vec3(0.0);
      glow += applyPaletteMode(texture(uTexture, clamp(pixelatedUv + vec2(texel.x, 0.0), vec2(0.0), vec2(1.0))).rgb) * 0.34;
      glow += applyPaletteMode(texture(uTexture, clamp(pixelatedUv - vec2(texel.x, 0.0), vec2(0.0), vec2(1.0))).rgb) * 0.34;
      glow += applyPaletteMode(texture(uTexture, clamp(pixelatedUv + vec2(texel.x * 2.0, 0.0), vec2(0.0), vec2(1.0))).rgb) * 0.18;
      glow += applyPaletteMode(texture(uTexture, clamp(pixelatedUv - vec2(texel.x * 2.0, 0.0), vec2(0.0), vec2(1.0))).rgb) * 0.18;
      glow += applyPaletteMode(texture(uTexture, clamp(pixelatedUv + vec2(0.0, texel.y), vec2(0.0), vec2(1.0))).rgb) * 0.10;
      glow += applyPaletteMode(texture(uTexture, clamp(pixelatedUv - vec2(0.0, texel.y), vec2(0.0), vec2(1.0))).rgb) * 0.10;

      float brightness = max(max(color.r, color.g), color.b);
      float glowMask = smoothstep(0.45, 1.0, brightness);
      if (uColoredGlowEnabled > 0.5) {
        float glowLuma = dot(glow, vec3(0.299, 0.587, 0.114));
        float glowSat = max(max(glow.r, glow.g), glow.b) - min(min(glow.r, glow.g), glow.b);
        vec3 glowChroma = glow - vec3(glowLuma);
        float brightClamp = 1.0 - smoothstep(0.72, 1.0, brightness) * 0.55;
        vec3 coloredGlow =
          vec3(glowLuma) * (0.30 + (1.0 - brightClamp) * 0.06) +
          glowChroma * (0.96 + smoothstep(0.03, 0.22, glowSat) * 0.42);
        color += coloredGlow * glowMask * uGlowStrength * brightClamp;
      } else {
        color += glow * glowMask * uGlowStrength;
      }
    }
  }

  color = clamp(color, 0.0, 1.0);

  float edgeBoost = clamp(uEdgeBoost, 0.0, 1.5);
  if (edgeBoost > 0.001) {
    float edge = computeSourceEdge(pixelatedUv, texel);
    float luminance = dot(color, vec3(0.299, 0.587, 0.114));
    float low = mix(uAnimeEdgeLow * 0.35, uAnimeEdgeLow, smoothstep(0.25, 0.65, luminance));
    float high = max(low + 0.02, uAnimeEdgeHigh);
    float edgeMix = smoothstep(low, high, edge) * min(edgeBoost, 1.0);
    color = mix(color, vec3(0.0), clamp(edgeMix, 0.0, 1.0));
  }

  finalColor = vec4(clamp(color, 0.0, 1.0), 1.0);
}
`;
